### ISSUE TITLE
groovy-ssh 2.11.0 release build issue

### ISSUE THREAD

**Issue by chenrui333** [int128/groovy-ssh#298]
### Environment info
Trying to build groovy-ssh 2.11.0, but run into the following error

```
Task 'shadowJar' not found in root project 'groovy-ssh' and its subprojects.
```

### Steps to reproduce
1. unzip the release tarball file
2. run `./gradlew tasks`

### Additional context

relates to https://github.com/Homebrew/homebrew-core/pull/120610
build log, https://github.com/Homebrew/homebrew-core/actions/runs/3919515473/jobs/6700598384

**Comment by chenrui333** [comment]
This would be the line also needs some update

https://github.com/int128/groovy-ssh/blob/c320e6cc97106b56c0c050421b0005631b6ec6ba/Dockerfile#L5

**Comment by chenrui333** [comment]
probably relates to https://github.com/int128/groovy-ssh/pull/294

**Comment by int128** [comment]
I'm trying to resolve this issue in https://github.com/int128/groovy-ssh/pull/299

**Comment by chenrui333** [comment]
yeah, the jar in the github releases are not working either. I can give the patch a try.

**Comment by chenrui333** [comment]
@int128 tried to build with `./gradlew shadowJar -Pversion=2.11.0`

but I have got this

```
$ java -jar cli/build/libs/gssh.jar --version
groovy-ssh-SNAPSHOT (java-11.0.17, groovy-3.0.13, jsch-0.2.5)
```

Let me know if i missed anything.

**Comment by chenrui333** [comment]
but the build works fine now.

**Comment by chenrui333** [comment]
I was trying to do something like this, but failed, any pointer?
```
$ gssh -e 'touch testfile' user@hostname 
2023-01-15 11:24:02.943 ERROR Error: groovy.lang.MissingPropertyException: No such property: testfile for class: script
2023-01-15 11:24:02.943 INFO  Run with -s or --stacktrace option to get the stack trace
```

```
$ gssh --stacktrace -e 'touch testfile' user@hostname
Exception in thread "main" groovy.lang.MissingPropertyException: No such property: testfile for class: script
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at script.run(script.groovy:1)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:254)
	at groovy.lang.GroovyShell.run(GroovyShell.java:360)
	at groovy.lang.GroovyShell.run(GroovyShell.java:339)
	at groovy.lang.GroovyShell.run(GroovyShell.java:166)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:170)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at org.hidetake.groovy.ssh.Main.main(Main.groovy:48)
```

**Comment by chenrui333** [comment]
looks like gssh 2.10.1 has the same issue
